-- 문제출처: https://programmers.co.kr/learn/courses/30/lessons/62284

SELECT DISTINCT CART_ID FROM CART_PRODUCTS A
WHERE  A.CART_ID IN(
   SELECT CART_ID
   FROM CART_PRODUCTS
   WHERE NAME = 'Milk'
)
AND A.CART_ID IN(
   SELECT CART_ID
   FROM CART_PRODUCTS
   WHERE NAME = 'Yogurt'
)